# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00c66e33c91f4e64285fba29c867dc16e6ac3468615398561c92dc826feafa2e4b67f5166b51e284887babd8dde4207036ec5db63a4839b3c50e866c7ef6891f

test:
  secret_key_base: cd92fa7828d935258a3a00ca428116a5a47c5fd9426fb8d6156ef071ef57db14f75941f0a6f8e1fc47635d284efd811eb14608c4b50e1b66974dfa62ee4cae43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
